### PR TITLE
Hotfix: button variant story

### LINKED ISSUE #629: Button - style: small Crashing in Storybook
## Environment

- `@launchpad/lp-components` version: 9.3.0
- `react` version: 6.4.22
- `node` version: ^18.12 || ^20.0

## Expected Behavior
Deployed storybook should display the Button - style: small correctly.

## Current Behavior
image

## Steps to Reproduce
Navigate to the [deployed Storybook](https://lp-components.herokuapp.com/storybook/index.html?path=/story/button--style-small)

## Suggested Solution
Fix the underlying issue, likely lives in the component or the story file.

### PR DESCRIPTION
**Pull request by chawes13**
Resolves #629 

**QA Steps**
- Checkout branch locally
- Run `yarn storybook`
- [x] `Button variant: small` story loads

## Author Checklist

- [ ] Add unit test(s)
- [x] Update version in package.json (see the [versioning guidelines](https://github.com/LaunchPadLab/opex-public/blob/main/gists/npm-package-guidelines.md#pull-requests-and-deployments))
- [ ] Update documentation (if necessary)
- [x] Add story to storybook (if necessary)
- [x] Assign dev reviewer

### CODE REVIEW

**Comment by chawes13** [comment]
@JoseWhite Got a few minutes to review this PR this week? Would love to get it in soon, thanks!

**Comment by JoseWhite** [comment]
Loaded the app locally and it renders correctly 👍 
I was thinking if it would make sense to add a jest spec for it, something like the snippet below to the `button.test.js` file.:
```
test('Button variant: small renders correctly', () => {
  render(
    <Button type="button" style={{ variant: 'small' }} >
    Submit
  </Button>
  )
  const button = screen.getByRole('button')

  expect(button).toBeVisible()
})
```

I looked into testing storybook stories and found this [jest add-on for storybook](https://storybook.js.org/addons/@storybook/addon-jest), it allows seeing test results in the storybook itself, perhaps it could make it easier to catch/prevent issues like this in the future.

**Review by JoseWhite — APPROVED** [review]
LGTM! 🚀 
Check separate comment about test snippet

**Comment by chawes13** [comment]
> Loaded the app locally and it renders correctly 👍 I was thinking if it would make sense to add a jest spec for it, something like the snippet below to the `button.test.js` file.:
> 
> ```
> test('Button variant: small renders correctly', () => {
>   render(
>     <Button type="button" style={{ variant: 'small' }} >
>     Submit
>   </Button>
>   )
>   const button = screen.getByRole('button')
> 
>   expect(button).toBeVisible()
> })
> ```
> 
> I looked into testing storybook stories and found this [jest add-on for storybook](https://storybook.js.org/addons/@storybook/addon-jest), it allows seeing test results in the storybook itself, perhaps it could make it easier to catch/prevent issues like this in the future.

We have a test for this! https://github.com/LaunchPadLab/lp-components/blob/bd1d293618fbe44fa07187863d9d28e2e1cc7f1a/test/forms/buttons/button.test.js#L89-L94

The jest add-on is interesting, thanks for sharing! I'm not sold on the value of including it – it wouldn't have prevented this issue here where the story was using an older syntax than the component/tests.

**Pull request merged**
