### PR TITLE
legacy-v4 [on hold]

### PR DESCRIPTION
**Pull request by dpikt**
Resolved issues:
* #293 
* #233 
* #325 
* Add legends for groups (PR #384)

### CODE REVIEW

**Comment by chawes13** [comment]
@dpikt Do you want to merge latest in here for me to use this as the base for my PR?

**Comment by dpikt** [comment]
@chawes13 yes plz!

**Comment by chawes13** [comment]
@dpikt Do you still want to keep `hideLabel`? I'm not sure that I understand the benefits?

**Comment by dpikt** [comment]
@chawes13 I think the idea was that passing `label={false}` was confusing. But since we're very used to it now I'm not sure if there's a big advantage to switching it up.

**Comment by chawes13** [comment]
Yeah I think that's fair and it is confusing. However, if we're going to introduce it in v4, shouldn't we strip out the backwards compatibility?

**Comment by dpikt** [comment]
@chawes13 up to you. It's technically in v4 because of the change to `RangeInput`. Personally I'd like to keep the required changes to a minimum and just adapt our best practices. But it's also a pretty easy change (find/replace `label={ false }`)

**Comment by chawes13** [comment]
@dpikt I took it out. I also fixed some linting errors in 66282a5 but didn't create a separate PR for that. LMK if any of the changes are a concern.

**Comment by dpikt** [comment]
Fine by me as long as you remember to put it in the migration guide 👍

**Comment by chawes13** [comment]
Well, technically we _don't_ have to mention it in the migration guide since it's not a change. I'll include the bit about `RangeInput` though

**Comment by dpikt** [comment]
@chawes13 can you remind me what the blockers are (if any) to merging this?

**Comment by chawes13** [comment]
@dpikt I believe none!

**Comment by dpikt** [comment]
😲

**Comment by dpikt** [comment]
I don't see a migration guide... 😏

**Comment by chawes13** [comment]
Hm, I don't have time today but can tackle it next week.

**Comment by dpikt** [comment]
Sweet 👌 a good first step might be to add the resolved issues to the description.

**Comment by chawes13** [comment]
@dpikt ...forgot about this

**Comment by dpikt** [comment]
@chawes13 can you review the migration guide? https://github.com/LaunchPadLab/lp-components/blob/79a0490524cd112850c88945daa18b9d9e915c3f/migration-guides/v4.0.0.md

**Pull request closed without merging**
