### PR TITLE
Pass props to label/error components and filter invalid properties on native inputs

### PR DESCRIPTION
**Pull request by chawes13**
… documentation

### CODE REVIEW

**Comment by chawes13** [comment]
The remaining props don't get passed from labeled field to the input label. Introducing this would require some more investigation re: what is actually passed down from a redux-form field. In the interim, I've removed the inappropriate example from the documentation and cleaned up the `LabeledField` story to demonstrate how to add actions to a custom label component.

**Comment by dpikt** [comment]
@chawes13 Hmm, I'd expect all the props to get passed down to the label component (aka this is a bug). Adding that functionality should be fine as long as we filter invalid props on the default component right?

**Comment by chawes13** [comment]
@dpikt Picking this up from a lonnnnnng time ago (use case just came up on Artlook). I agree, we should pass all props down. I was thinking there might be some edge cases around `aria-` attributes but thinking through some use cases didn't seem to raise any red flags

**Comment by chawes13** [comment]
but I haven't implemented that yet 😆

**Comment by dpikt** [comment]
Haha I didn't catch that. Consider it a major vote of confidence!

**Comment by chawes13** [comment]
Despite the vote of confidence, would still appreciate if you could take another look!

**Comment by dpikt** [comment]
This just fixed a bug for me on AZ!

**Comment by dpikt** [comment]
(thought you might like to know)

**Comment by chawes13** [comment]
🔥 donate to my patreon

**Comment by dpikt** [comment]
`the author of lp-components is looking for a good job -)`

**Pull request merged**
