### PR TITLE
Add `hideLabel` prop

### LINKED ISSUE #222: Add `hideLabel` prop as alias for label={false}

### PR DESCRIPTION
**Pull request by rkillackey**
Resolves #222

### CODE REVIEW

**Comment by dpikt** [comment]
@rkillackey looks good. Once the other PR is merged, create a `v4` branch for the next version and use that as the base of this PR instead 🎉

**Comment by dpikt** [comment]
@rkillackey sweet. Let's wait to merge this until the other enhancements are done.

**Comment by dpikt** [comment]
(the v4 branch I mean)

**Comment by rkillackey** [comment]
Yep!

**Pull request merged**
