### PR TITLE
Add valueGetter to Table component

### PR DESCRIPTION
**Pull request by mwislek**
This PR adds a `valueGetter` prop to the `<SortedTable>` component to facilitate creating columns whose data is derived, typically from multiple properties of a table row's data. The `valueGetter` prop is a function that is passed row data and returns the derived data value.

## Author Checklist

- [x] Add unit test(s)
- [x] Update version in package.json
- [x] Update documentation (if necessary)
- [x] Add story to storybook (if necessary)
- [x] Assign dev reviewer

### CODE REVIEW

**Comment by mwislek** [comment]
@dpikt be brutal with your review! My confidence level is at 62.3% with this change.

**Comment by mwislek** [comment]
@dpikt Documentation manually updated. Should be good to go.

**Comment by dpikt** [comment]
Travis is jacked up for some reason. I'll merge.

**Comment by dpikt** [comment]
https://travis-ci.org/github/LaunchPadLab/lp-components/builds/708061595

**Comment by mwislek** [comment]
Excellent. Thanks David!

M

**Pull request merged**
