### PR TITLE
Disable click events

### LINKED ISSUE #338: Do not allow keyboard or click events for submitting / disabled buttons
While CSS styling often has `pointer-events: none` set for submitting, if using a keyboard it's still possible to press the button. `Redux-Form` might protect against this but we should override this with a `noop` by default

### PR DESCRIPTION
**Pull request by chawes13**
Resolves #338

### CODE REVIEW

**Comment by dpikt** [comment]
This might be considered a patch 🤔

**Comment by chawes13** [comment]
Yeah... I think technically it could be considered a bug. Want me to switch the base?

**Comment by dpikt** [comment]
👍

**Comment by chawes13** [comment]
Rebased and ready! Can you give me a quick sanity check that things aren't wildly wrong?

**Pull request merged**
